name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
          
      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install

      # Optional: If you don't need build steps, skip them
      - name: Build frontend (if needed)
        run: |
          cd frontend
          # Add build commands if any (currently not required for static HTML)
          
      - name: Build backend (if needed)
        run: |
          cd backend
          # Add backend build steps if any

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests (if applicable)
        run: |
          cd frontend
          # Add test commands if you have any
          cd ../backend
          # Add backend test commands

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cloud (example with AWS)
        run: |
          echo "Deploying the app to the cloud provider"
          # Add your deployment commands here (e.g., AWS CLI commands, Azure, GCP)
          # Example for AWS deployment
          aws s3 sync ./frontend/ s3://your-bucket-name --delete
          aws s3 sync ./backend/ s3://your-bucket-name --delete
          
      - name: Manual approval step before deploying to production
        run: echo "Approval is needed before deploying to production"
        # You can integrate GitHub's manual approval here
