name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
          
      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install

      # Optional: If you don't need build steps, skip them
      - name: Build frontend (if needed)
        run: |
          cd frontend
          # Add build commands if any (currently not required for static HTML)
          
      - name: Build backend (if needed)
        run: |
          cd backend
          # Add backend build steps if any

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests (if applicable)
        run: |
          cd frontend
          # Add test commands if you have any
          cd ../backend
          # Add backend test commands

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy backend to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cvvmt6qdbo4c738b91k0/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"

      - name: Deploy frontend to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cvvnajmuk2gs73dg1usg/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"

      
      - name: Manual approval step before deploying to production
        run: echo "Approval is needed before deploying to production"
        # You can integrate GitHub's manual approval here (optional)
